server:
  port: 8003

spring:
  application:
    name: cloud-provider-payment
  cloud:
    zookeeper:
      connect-string: localhost:2181

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_2020?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 5780

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.emon.cloud.entities

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
#  instance:
#    instance-id: payment-8003
#    prefer-ip-address: true
#    lease-renewal-interval-in-seconds: 2
#    lease-expiration-duration-in-seconds: 1